apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: movie-analyzer

# Resources to include in this kustomization
resources:
  # Namespace
  - namespace.yaml
  
  # Backend
  - backend/secret.yaml
  - backend/deployment.yaml
  - backend/service.yaml
  
  # Frontend
  - frontend/deployment.yaml
  - frontend/service.yaml
  - frontend/ingress.yaml
  
  # Model
  - model/deployment.yaml
  - model/service.yaml
  
  # PostgreSQL
  - postgres/secret.yaml
  - postgres/configmap.yaml
  - postgres/pvc.yaml
  - postgres/deployment.yaml
  - postgres/service.yaml

# Common labels applied to all resources
commonLabels:
  app.kubernetes.io/part-of: movie-analyzer
  app.kubernetes.io/managed-by: kustomize

# Namespace to deploy all resources into
namespace: movie-analyzer 